FROM python:3.9-slim

WORKDIR /app

# Install Chromium and chromedriver for Linux
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/jobs

COPY scrapers /app/scrapers
COPY main.py /app/main.py

CMD [ "python", "main.py" ]
